<div id="FooterBox">
        
    <img id="FooterImageLeft" src="../../img/golders-logo-small.png" alt="Golder Logo" />

	<div id="Footer">

        <!--div id="FooterContactInfo">
            <span id="CallUs" class="ContactItem">CALL US: (07) 4622 161</span>
            <span>
                <a id="EmailUs" class="ContactItem" href='mailto:goldersromaorders@bigpond.net.au'>EMAIL US: GoldersRomaOrders@bigpond.net.au</a>
		    </span>
		</div-->
		
        <div>
            <p>
                Call Us: (07) 4622 161 
                <label class="divider">|</label>
                Email Us: <a id="email" href='mailto:goldersromaorders@bigpond.net.au'>GoldersRomaOrders@bigpond.net.au</a>
            </p>
        </div>	
        	
        <div>
            <p>Copyright &copy; 2013 Golders of Roma. All Rights Reserved. </p>
        </div>

    </div>

    <img id="FooterImageRight" src="../../img/golders-logo-small.png" alt="Golder Logo" />

</div>
