
<div id="HdrBox">
    <div id="HdrImages">
        <img id="HdrImageLeft"      src="../../img/hdr-meet.png"  alt="Meet Golders" title=""/>
        <img id="HdrImageCenter"    src="../../img/hdr-logo.png"  alt="Golders" title=""/>
        <img id="HdrImageRight"     src="../../img/hdr-phone.png" alt="Golders Phone" title=""/>
        <div style="clear:both"></div>
    </div>
    <div id="HdrActionBar">
        <a class="Left First" href="../../default.aspx">Home</a>
        <a class="Left" href="../../orders.aspx">Order Management</a>
        <a class="Left" href="./manage-users.aspx">Manage Users</a>
        <!--a class="Left" href="javascript:alert('Admin Tools Coming!');">Admin Tools</a>-->
        <a id="HdrUserAction" class="Right" href="../../login.aspx">Sign In</a>
    </div>
</div>