<div id="HdrBox">
    <div id="HdrImages">
        <img id="HdrImageLeft"      src="../../img/hdr-meet.png"  alt="Meet Golders" title=""/>
        <img id="HdrImageCenter"    src="../../img/hdr-logo.png"  alt="Golders" title=""/>
        <img id="HdrImageRight"     src="../../img/hdr-phone.png" alt="Golders Phone" title=""/>
        <div style="clear:both"></div>
    </div>
    <div id="HdrActionBar">
         <a id="HdrUserAction" class="Right" href="~/login.aspx">Sign In</a>
    </div>
</div>