<div id="HdrBox">

	<div id="Hdr">
        <img id="HdrImage" src="img/hdr-logo.png"  alt="Golders" title=""/>
        <!--img id="HdrImageRight"	src="img/hdr-right.jpg" alt="Golders" /-->

		<!--
		<div id="HdrActionBar">
			<a href="default_new.aspx">Main Site</a>
			<a href="services.aspx"	>Services</a>
			<a href="blog.aspx"		>Blog</a>
			<a href="about.aspx"	>About</a>
			<a href="login.aspx"	>Log Out</a>
            <a href="ajax-test.aspx">AJAX Test</a>
		</div>
 		-->
 		
        <div id="HdrActionBar">
             <a id="HdrUserAction" class="Right" href="~/login.aspx">Sign In</a>
        </div>

    </div>

</div>